[package]
name = "chaindev"
version = "0.2.1"
edition = "2021"
authors = ["hui.fan@mail.ru","fhfanhui@gmail.com"]
description = "Powerful development and testing utils for blockchain developers."
homepage = "https://github.com/rust-util-collections/chaindev"
repository = "https://github.com/rust-util-collections/chaindev"
keywords = ["blockchain", "tendermint", "substrate", "development"]
license = "GPL-3.0"
# build = "build.rs"

[dependencies]
nix = "0.26.1"
toml_edit = "0.15.0"
rand = "0.8.5"
once_cell = "1.16.0"
parking_lot = "0.12.1"

serde_json = "1.0.89"
serde = { version = "1.0.148", features = ["derive"] }

ruc = { version = "3.0.3", features = ["cmd","ssh"] }

# vsdb = { path = "../vsdb/wrappers", default-features = false, features = ["bcs_codec", "sled_engine", "sled_compress"] }
vsdb = { version = "0.48.6", default-features = false, features = ["bcs_codec", "sled_engine", "sled_compress"] }

tendermint = { version = "0.28.0", optional = true }
tendermint-config = { version = "0.28.0", optional = true }

[features]
default = ["tendermint_based"]

substrate_based = []
tendermint_based = ["tendermint","tendermint-config"]

unix_abstract_socket = []
