[package]
name = "chaindev"
version = "0.1.0"
edition = "2021"
authors = ["fhfanhui@gmail.com"]
license = "GPLv3"
#build = "build.rs"

[dependencies]
nix = "0.25.0"
toml_edit = "0.14.4"
rand = "0.8.5"
once_cell = "1.14.0"
parking_lot = "0.12.1"

serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

vsdb = "0.47.0"
ruc = { version = "3.0.0", features = ["cmd","ssh"] }

tendermint = { git = "https://github.com/rust-util-collections/tendermint-rs", tag = "v0.25.0-gsc-p3", optional = true }
tendermint-config =  { git = "https://github.com/rust-util-collections/tendermint-rs", tag = "v0.25.0-gsc-p3", optional = true }

[features]
default = ["tendermint_based","unix_abstract_socket"]
substrate_based = []
tendermint_based = ["tendermint","tendermint-config"]
unix_abstract_socket = []
